"""markdown

Revision ID: 2e9bc3bee7e2
Revises: 43a94d68d59e
Create Date: 2016-01-31 22:37:16.193000

"""

# revision identifiers, used by Alembic.
revision = '2e9bc3bee7e2'
down_revision = '43a94d68d59e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
