"""add avatar_hash

Revision ID: 43a94d68d59e
Revises: 38c4e85512a9
Create Date: 2016-01-31 11:49:57.431000

"""

# revision identifiers, used by Alembic.
revision = '43a94d68d59e'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
