"""add post's title

Revision ID: 687013d4fc82
Revises: dcb51bbc8161
Create Date: 2016-02-03 14:42:32.658000

"""

# revision identifiers, used by Alembic.
revision = '687013d4fc82'
down_revision = 'dcb51bbc8161'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_timestamp'), 'status', ['timestamp'], unique=False)
    op.add_column(u'posts', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'posts', 'title')
    op.drop_index(op.f('ix_status_timestamp'), table_name='status')
    op.drop_table('status')
    ### end Alembic commands ###
